# Generated by Django 5.1.4 on 2024-12-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distributeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=8, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('sex', models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=1)),
                ('nationality', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('cin', models.CharField(blank=True, max_length=12, null=True)),
                ('phone_number', models.CharField(max_length=9)),
                ('adress', models.CharField(max_length=200)),
                ('postal_code', models.CharField(max_length=3)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
